### ISSUE TITLE
Pushbots overrides didRegisterForRemoteNotificationsWithDeviceToken method on ios7

### ISSUE THREAD

**Issue by Bergrebell** [pushbots/phonegap#10]
I've built an phonegap app using pushbots which runs just finde on ios8! But when I try to run the app on my old Iphone4 running ios 7.1.2 it gives me a warning when compiling the app:

> ld: warning: instance method
> 'application:didRegisterForRemoteNotificationsWithDeviceToken:' in
> category from
> /Users/name/Library/Developer/Xcode/DerivedData/ComfortUnifr-dcicazmskkffevfoirbwgxqnobiq/Build/Intermediates/Comfort.build/Debug-iphoneos/ComfortUnifr.build/Objects-normal/armv7/PushbotsDelegate.o
> overrides method from class in
> /Users/name/Library/Developer/Xcode/DerivedData/ComfortUnifr-dcicazmskkffevfoirbwgxqnobiq/Build/Intermediates/Comfort.build/Debug-iphoneos/ComfortUnifr.build/Objects-normal/armv7/AppDelegate.o

It seems like pushbots is overriding a built in method. Here is the method in the pushbots appdelegate:

```
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
    // This method will be called everytime you open the app
    // Register the deviceToken on Pushbots
    [[Pushbots sharedInstance] registerOnPushbots:deviceToken];
    NSLog(@"Registered token is %@", deviceToken);
}
```

and here the other one: 

```
#ifndef DISABLE_PUSH_NOTIFICATIONS

    - (void)                                 application:(UIApplication*)application
        didRegisterForRemoteNotificationsWithDeviceToken:(NSData*)deviceToken
    {
        // re-post ( broadcast )
        NSString* token = [[[[deviceToken description]
            stringByReplacingOccurrencesOfString:@"<" withString:@""]
            stringByReplacingOccurrencesOfString:@">" withString:@""]
            stringByReplacingOccurrencesOfString:@" " withString:@""];

        [[NSNotificationCenter defaultCenter] postNotificationName:CDVRemoteNotification object:token];
    }

    - (void)                                 application:(UIApplication*)application
        didFailToRegisterForRemoteNotificationsWithError:(NSError*)error
    {
        // re-post ( broadcast )
        [[NSNotificationCenter defaultCenter] postNotificationName:CDVRemoteNotificationError object:error];
    }
#endif
```

I'm not quite sure what to do now ... commenting out the method in the normal appdelegate didn't do the trick ... any advice?

**Comment by AbdullahDiaa** [comment]
Issue is fixed in 1.3.x with **MethodSwizzle**
