### ISSUE TITLE
Error after update Xcode and ios9

### ISSUE THREAD

**Issue by magic1979** [pushbots/phonegap#11]
hi all,
after update Xcode 7.0 and IOS 9 i have this error

after cordova plugin add com.pushbots.push

Undefined symbols for architecture i386: 
"_OBJC_CLASS_$_Pushbots", referenced from: 
objc-class-ref in PushbotsDelegate.o 
objc-class-ref in PushbotsPlugin.o 
(maybe you meant: _OBJC_CLASS_$_PushbotsPlugin) 
ld: symbol(s) not found for architecture i386 
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Can Help me Please ?

Thanks a lot

**Comment by AbdullahDiaa** [comment]
Should be fixed in 1.2.8
