### ISSUE TITLE
getToken not found

### ISSUE THREAD

**Issue by Memleak2** [pushbots/phonegap#12]
Error on method not found when i try to call "getToken"
Any idea?

**Comment by schreyers** [comment]
@Memleak2 I had the same issue but hey updated the code on phonegap npm. If you are using phonegap build then you need to:

In config.xml add replace your old plugin line with:

<gap:plugin name="pushbots-cordova-plugin" source="npm" />

Then when you call for the device_token it will work. You need to call getToken after the initialize method.

Hope that helps

**Comment by AbdullahDiaa** [comment]
Issue is fixed in 1.3.x by adding on **registered** event.
