### ISSUE TITLE
initializeWithAppIdAndSenderId blocked the main thread

### ISSUE THREAD

**Issue by hejosadi** [pushbots/phonegap#13]
10-08 01:44:37.890    1086-1086/? W/PluginManager﹕ THREAD WARNING: exec() call to PushbotsPlugin.initializeWithAppIdAndSenderId blocked the main thread for 151ms. Plugin should use CordovaInterface.getThreadPool().
that message appears and can not initialized 
Android

**Comment by AbdullahDiaa** [comment]
Issue is fixed in 1.3.x
