### ISSUE TITLE
Xcode 7.1 archive error

### ISSUE THREAD

**Issue by cmboros** [pushbots/phonegap#15]
I got this 2 error when i try to archive with xCode 7.1
ld: bitcode bundle could not be generated because 'app/Plugins/com.pushbots.push/Pushbots.framework/Pushbots(PBAlias.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64

Ld /Users/user/Library/Developer/Xcode/DerivedData/app-eizjmqhelknstvdsejwynhuxjbzs/Build/Intermediates/ArchiveIntermediates/App\ Name/IntermediateBuildFilesPath/App\ Name.build/Release-iphoneos/App\ Name.build/Objects-normal/armv7/App\ Name normal armv7
    cd /Users/user/Code/build/ios/project
    export IPHONEOS_DEPLOYMENT_TARGET=7.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.1.sdk -L/Users/user/Library/Developer/Xcode/DerivedData/app-eizjmqhelknstvdsejwynhuxjbzs/Build/Intermediates/ArchiveIntermediates/App\ Name/BuildProductsPath/Release-iphoneos -F/Users/user/Library/Developer/Xcode/DerivedData/app-eizjmqhelknstvdsejwynhuxjbzs/Build/Intermediates/ArchiveIntermediates/App\ Name/BuildProductsPath/Release-iphoneos -FApp\ Name/Plugins/com.pushbots.push -filelist /Users/user/Library/Developer/Xcode/DerivedData/app-eizjmqhelknstvdsejwynhuxjbzs/Build/Intermediates/ArchiveIntermediates/App\ Name/IntermediateBuildFilesPath/App\ Name.build/Release-iphoneos/App\ Name.build/Objects-normal/armv7/App\ Name.LinkFileList -miphoneos-version-min=7.0 -dead_strip -fembed-bitcode -Xlinker -bitcode_verify -Xlinker -bitcode_hide_symbols -Xlinker -bitcode_symbol_map -Xlinker /Users/user/Library/Developer/Xcode/DerivedData/app-eizjmqhelknstvdsejwynhuxjbzs/Build/Intermediates/ArchiveIntermediates/App\ Name/BuildProductsPath/Release-iphoneos -weak_framework CoreFoundation -weak_framework UIKit -weak_framework AVFoundation -weak_framework CoreMedia -weak-lSystem -ObjC -fobjc-arc -fobjc-link-runtime -framework AssetsLibrary /Users/user/Library/Developer/Xcode/DerivedData/app-eizjmqhelknstvdsejwynhuxjbzs/Build/Intermediates/ArchiveIntermediates/App\ Name/BuildProductsPath/Release-iphoneos/libCordova.a -framework CoreGraphics -framework MobileCoreServices -framework Foundation -weak_framework ImageIO -weak_framework CoreImage -weak_framework CoreVideo -weak_framework CoreMedia -framework Pushbots -framework CoreLocation -framework SystemConfiguration -framework CoreTelephony -weak_framework Social -weak_framework MessageUI -Xlinker -dependency_info -Xlinker /Users/user/Library/Developer/Xcode/DerivedData/app-eizjmqhelknstvdsejwynhuxjbzs/Build/Intermediates/ArchiveIntermediates/App\ Name/IntermediateBuildFilesPath/App\ Name.build/Release-iphoneos/App\ Name.build/Objects-normal/armv7/App\ Name_dependency_info.dat -o /Users/user/Library/Developer/Xcode/DerivedData/app-eizjmqhelknstvdsejwynhuxjbzs/Build/Intermediates/ArchiveIntermediates/App\ Name/IntermediateBuildFilesPath/App\ Name.build/Release-iphoneos/App\ Name.build/Objects-normal/armv7/App\ Name

ld: bitcode bundle could not be generated because 'app/Plugins/com.pushbots.push/Pushbots.framework/Pushbots(PBAlias.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Any fix on this?

**Comment by jordmax12** [comment]
I am having this issue as well.

**Comment by amrsobhy** [comment]
We have confirmed this problem with Xcode 7.1. We are working on a fix.

**Comment by optikalefx** [comment]
I've got a client asking me when we'll be able to push to the app store, any ideas on this one? Can we help at all?

**Comment by jordmax12** [comment]
@optikalefx I was able to get around this by setting the value for 'ENABLE_BITCODE' in build settings to false. Not a fix by any means, but at least until Pushbots fixes it, it will work for you.

**Comment by optikalefx** [comment]
@jordmax12 thank you so much!

**Comment by xndrdev** [comment]
@jordmax12 Had the same issue with pushbots. Thank you a lot. Saved my life!
