### ISSUE TITLE
Notification when app is not loaded

### ISSUE THREAD

**Issue by timwright35** [pushbots/phonegap#17]
Hello, I have found that if the app has been loaded before but is not loaded at the moment, ie killed from memory, that notifications do not come through.  They come through if the app is currently in the foreground and if the app was in the foreground but lost focus. 

Is there someway to make it so when the app is not loaded that the notifications are still coming in?

**Comment by igorrino** [comment]
i have the same problem, How do you correct it ?

**Comment by timwright35** [comment]
No clue, I have no if it is possible based on how phonegap etc run on a device.

**Comment by AbdullahDiaa** [comment]
Should be fixed with 1.3.0
