### ISSUE TITLE
Invalid Date error

### ISSUE THREAD

**Issue by optikalefx** [pushbots/phonegap#18]
When calling getToken. This is testing on an actual device (iPhone 6, mobile safari, iOS 9)

```
[Log] Error in Success callbackId: PushbotsPlugin1379922146 : RangeError: Invalid Date (cordova.js, line 312)
[Error] RangeError: Invalid Date
    callbackFromNative
    (anonymous function)
    nativeEvalAndFetch
    nativeCallback
    (anonymous function)
```

**Comment by optikalefx** [comment]
Sort of, its hard for me to tell when this happens. But i'm getting this error repeatedly. Trying to nail down where this might be happening.

**Comment by AbdullahDiaa** [comment]
Can you please update to 1.3.0 and try this method instead of getToken:

``` javascript
Pushbots.on("registered", function(token){
    console.log("Registration Id:" + token);
});
```

**Comment by optikalefx** [comment]
oh wow this changed a lot. I'm not a fan of the change that requires me to have a global Pushbots off of initialize. Now I have 2 globals. PushbotsPlugin and PushBots

**Comment by optikalefx** [comment]
I'll let you know how this goes, thanks!

**Comment by optikalefx** [comment]
seems to be ok. Still not happy about having 2 globals
