### ISSUE TITLE
Catch Notification when App is in Foreground via JS

### ISSUE THREAD

**Issue by kevincobain2000** [pushbots/phonegap#19]
Is there a way to catch the following event via Javascript?

https://github.com/pushbots/phonegap/blob/master/src/ios/PushbotsDelegate.m#L16

**Comment by kevincobain2000** [comment]
something like https://github.com/pushbots/phonegap/blob/master/www/pushbots.js#L81

```
Pushbot.receivedNotification(function(){
   // do something inside the app via js
})
```

**Comment by AbdullahDiaa** [comment]
You can use this listener to monitor received notifications in iOS and Android in **1.3.x**:

`````` javascript
// Should be called once app receive the notification
Pushbots.on("notification:received", function(data){
    console.log("received:" + JSON.stringify(data));
});```
``````

**Comment by kevincobain2000** [comment]
@AbdullahDiaa Awesome man thanks
