### ISSUE TITLE
Docs Fix s/registration/registered

### ISSUE THREAD

**Issue by kevincobain2000** [pushbots/phonegap#22]
right at the bottom it says `registration`, I think it should be `registered`

https://pushbots.com/developer/docs/phonegap-sdk-integration

https://github.com/pushbots/phonegap/blob/master/www/pushbots.js#L55

**Comment by amrsobhy** [comment]
Thanks for reporting this. Shall be updated shortly.

**Comment by kevincobain2000** [comment]
:+1: Thanks

**Comment by amrsobhy** [comment]
Fixed
