### ISSUE TITLE
iOS Badge Handling - Functions do not exist

### ISSUE THREAD

**Issue by John-C2** [pushbots/phonegap#23]
According to the documentation you can use the following functions to handle iOS badges.

//Reset Badge
Pushbots.resetBadge();
//Set badge
Pushbots.setBadge(10);

but both return errors that the functions to do not exist.  Looking in the .js file for pushbots I can see that there are no functions that include the word "badge".  Other functions like Pushbots.updateAlias() work fine and the corresponding functions are present in the .js file.

**Comment by buddywa** [comment]
Yes I am also having this issue. I have badges which I can not get rid of.

**Comment by amrsobhy** [comment]
Thanks for reporting this. I confirm the bug we will push an update shortly to fix this.
