### ISSUE TITLE
Register callbacks are lost when calling the updateAlias() or tag()

### ISSUE THREAD

**Issue by lricoy** [pushbots/phonegap#24]
Hi. I am having some troubles using the .updateAlias() and .tag() methods of the phonegap plugin. I am using Ionic and it appears that when I call these methods, the Pushbots object does not execute the callbacks I have set using Pushbots.on("notification:clicked") anymore. It works fine if I remove both the calls to updateAlias() and tag()

**Comment by amrsobhy** [comment]
Where do you run these calls? Is that in the same file where PushBots is initialised?

**Comment by lricoy** [comment]
Yes. I will show you a sample.

**Comment by lricoy** [comment]
The problem occurs on the IIFE checkExistingCredentials().

```
angular.module('myApp')
.run(function($ionicPlatform, $rootScope, $state, $http, PushBotHelper, Auth, localStorageService) {
  $ionicPlatform.ready(function() {

    if(PushbotsPlugin){
      var Pushbots = PushbotsPlugin.initialize("5693aa23177959fd328b4567", {"android":{"sender_id":"164547083981"}});

      // First time registration
      // This will be called on token registration/refresh with Android and with every runtime with iOS
      Pushbots.on("registered", function(token){
          console.log("Registration Id:" + token);
      });

      Pushbots.getRegistrationId(function(token){
          console.log("Registration Id:" + token);
      });

      // Should be called once app receive the notification
      Pushbots.on("notification:received", function(data){
          console.log("received:" + JSON.stringify(data));
          $rootScope.$emit('notification:received', {data: data});
      });

      // Should be called once the notification is clicked
      // **important** Doesn't work with iOS while app is closed, will be fixed in 1.3.1
      Pushbots.on("notification:clicked", function(data){
          console.log("clicked:" + JSON.stringify(data));
          $rootScope.$emit('notification:received', {data: data});

          if(data.jobId){
            $state.go('tab.job-detail', {jobId: data.jobId});
          }
      });
    }

    // Check if token already exists
    (function checkExistingCredentials(){
      console.log('Checking for token...');
      var token = localStorageService.get('token');
      if(token){
        $http.defaults.headers.common.Authorization = 'Bearer ' + token;
        $rootScope.$emit('auth:login_success');

        // Update the current user to use with the PUSH options
        // If exists, update the user object
        Auth.getCurrentUser().$promise.then(function(currentUser){
          var currentPlatform = ionic.Platform.isIOS() ? 'iOS' : 'android';
          console.log('The current user is:' + currentUser.name, currentPlatform);
          currentUser.app_config.mobile_os_version = currentPlatform;
          currentUser.$update();

          // Update the PUSH options
          Pushbots.updateAlias(currentUser._id);
          Pushbots.tag(currentUser.client_id);

        });

      }
    })();

  });
});
```

**Comment by drigolin** [comment]
Me too. In my app seems that updateAlias and tag method doesn't work. Application registration never receive correct tag or alias. Those methods can be called anytime in the future to change alias and tag whenever we want? cordova 6 and latest plugin. Android-22 as target

**Comment by AbdullahDiaa** [comment]
This should be fixed in 1.3.6.
You can now update the alias anywhere in your app
`window.plugins.PushbotsPlugin.updateAlias("Test");`

**Comment by sultanahmedkhan** [comment]
callback in window.plugins.PushbotsPlugin.on  and window.plugins.PushbotsPlugin.getRegistrationId is not working . My device has registered on the pushbot but in my app i am not getting token.
i am using pushbot version 1.4.1

window.plugins.PushbotsPlugin.on("registered", function(token){
    console.log("Registration Id:" + token);
});

window.plugins.PushbotsPlugin.getRegistrationId(function(token){
        console.log("Registration Id:" + token);
      });

**Comment by jfrubio** [comment]
Hi.
Did you fix the problem? Wish version of pushbots-cordova-plugin do you use? And phonegap-version plugin version?
My device appears registered on pushbots panel but PushbotsPlugin.on("registered"... never occurs.
Thanks

**Comment by lricoy** [comment]
I have not. The project was discontinued and I haven't tried again ever since.
