### ISSUE TITLE
Push notification when app is closed

### ISSUE THREAD

**Issue by drigolin** [pushbots/phonegap#27]
I cannot receive notification when app is closed.
Cordova v6 pushbots-plugin v1.3.1 and Android api v22 as target.
Both running on Emulator or Devices  push notifications when app isn't running are lost.
I followed the guide (video tutorial) and I have updated also the .xml files with AppID and Google Sender id.

When app is running or in foreground push works as expected.

**Comment by amrsobhy** [comment]
First of all, can you use the latest version 1.3.5
Second, What's your android version? 
Third, can you show us this in a screencast to be able to reproduce the problem?

**Comment by drigolin** [comment]
Sorry I'm using 1.3.5
Android version on my phone is 6.0 , but i have built my cordova project for API Level 22 (Android 5.1). I used also Android 4.1 on emulator but the results are the same.
I can't do a screencast in case of push notification not arriving because nothing happen on the phone. Last thing I can do is using your sample phonegap application, and check if that is working. I was thinking that maybe somenthing in Android.xml is missing not telling the OS to "link" my application to the notification.

**Comment by drigolin** [comment]
Update on that issue. On a Android 4.1.1 tablet it works fine. Seem related to Android 6.0. I'm using a Huawei Mate 8.

**Comment by AbdullahDiaa** [comment]
This should be fixed in 1.3.6 for iOS.
