### ISSUE TITLE
Update alias without restart app.

### ISSUE THREAD

**Issue by murilocbs** [pushbots/phonegap#28]
Friends,

When i use on click jquery function to call Pushbots.tag("active") not work.

Its work only when i use this:
Pushbots.on("registered", function(token){
  Pushbots.untag("inactive");
  Pushbots.tag("active");
}

Who can i set in real time, without restart app? Like this:
$('.button').on('click', function() {
   Pushbots.untag("inactive");
   Pushbots.tag("active");
});

**Comment by murilocbs** [comment]
can i use onClick to set alias?

**Comment by AbdullahDiaa** [comment]
This has been fixed in 1.3.6, you don't need to restart the app anymore.
`window.plugins.PushbotsPlugin.updateAlias("Test");`
