### ISSUE TITLE
setAlias not working

### ISSUE THREAD

**Issue by bplogan** [pushbots/phonegap#3]
I am using phonegap build, I can receive push notifications to my app when I send to all devices.  I want to send to specific devices so I am trying to utilize the setAlias function.

```
onDeviceReady: function() {
        app.receivedEvent('deviceready');
        if(PushbotsPlugin.isiOS()){
            PushbotsPlugin.initializeiOS("554e2.....");
        }
        if(PushbotsPlugin.isAndroid()){
            PushbotsPlugin.initializeAndroid("554e2......", "77.....");
        }
        PushbotsPlugin.setAlias("aliasname");

    },
```

The device registers in my dashboard but the alias is always blank.  What am I doing wrong?

**Comment by amrsobhy** [comment]
The problem is probably that setAlias function is being executed immediately before device is fully registered. Try to set time out for 30 seconds or a minute before you set the alias and see if it works.

**Comment by lasdou** [comment]
You must use updateAlias method in current version

**Comment by huzoorbux** [comment]
How to know that user clicked on a notification i am trying it since 3 days not able to configure please help.

**Comment by joanebrown** [comment]
I have this problem too, but with one particularity: Only happens when I try this with the compiled APK. When I use `ionic run android --consolelogs --livereload` works perfectly (even without the timeout)

    var name = "myAlias";
    window.plugins.PushbotsPlugin.on("registered", function(token) {

		$timeout(function() {
			// works well.
			alert(name); 

			// doesn't work. Device with blank alias.
			window.plugins.PushbotsPlugin.setAlias(name);

		}, 30000);

     });

I really appreciate any help :-)
---
**Environment:**

OS: *Android 5.0*
Framework: *Ionic*

**Comment by joanebrown** [comment]
@huzoorbux 

You can do that with:

    window.plugins.PushbotsPlugin.on("notification:clicked", function(data) {
        ...
    });
