### ISSUE TITLE
Pushbots with iOS build issue

### ISSUE THREAD

**Issue by srbasraa** [pushbots/phonegap#30]
Hey guys,
       So pushbots used to perfectly fine previously but ever since they updated their api and version, everything has gone south. i had to update my api and now i can't build my ios app with pushbots plugin
this is what i have done to narrow down the issue
- updated my cordova to 6.0
- created a fresh new project
- added ios platform
- build ios platform and it works
- added pushbots-cordova-plugin
- build ios platform and it never works. always give me this error:
  
  Ld /users/lemotech/documents/untitled\ folder/imed3/platforms/ios/build/emulator/HelloCordova.app/HelloCordova normal i386
  (1 failure)
  ERROR building one of the platforms: Error code 65 for command: xcodebuild with args: -xcconfig,/users/lemotech/documents/untitled folder/imed3/platforms/ios/cordova/build-debug.xcconfig,-project,HelloCordova.xcodeproj,ARCHS=i386,-target,HelloCordova,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/users/lemotech/documents/untitled folder/imed3/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/users/lemotech/documents/untitled folder/imed3/platforms/ios/build/sharedpch
  You may not have the required environment or OS to build this project
  Error: Error code 65 for command: xcodebuild with args: -xcconfig,/users/lemotech/documents/untitled folder/imed3/platforms/ios/cordova/build-debug.xcconfig,-project,HelloCordova.xcodeproj,ARCHS=i386,-target,HelloCordova,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/users/lemotech/documents/untitled folder/imed3/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/users/lemotech/documents/untitled folder/imed3/platforms/ios/build/sharedpch

am i missing something basic here? please help out, thanks

**Comment by AbdullahDiaa** [comment]
Please make sure you're using Xcode 7.0+
