### ISSUE TITLE
Registration Fail with the new update (cordova-ionic) -iOS-

### ISSUE THREAD

**Issue by kldoon** [pushbots/phonegap#32]
With the new update 1.3.6, the Plugin is failing to register new devices on iOS, i think the plugin crashes.
I was not able to get more details, 
but i had to roll back to 1.3.5 to get it working

**Comment by AbdullahDiaa** [comment]
Can you please make sure you've followed instructions in upgrade guide:
https://pushbots.com/developer/docs/phonegap-upgrade

**Comment by kldoon** [comment]
No i didn't follow that, i will give it a try,
