### ISSUE TITLE
Re-Register not possible after unregister()

### ISSUE THREAD

**Issue by tfohlmeister** [pushbots/phonegap#34]
I want to allow my users to opt-in and -out of push notifications through a simple setting.
What works great right now is the opt-out via `.unregister();`
What does not work is being able to re-register. As there is no `.register()` function I just tried to re-initialise the plugin with `$window.plugins.PushbotsPlugin.initialize(...);`. 

Apparently this plugin works as a singleton, because if I run the above a second time, my log shows something like `[Pushbots] :sharedInstanceWithAppId 3123123123123123.`.

Any idea on how to register again after unregister without restarting the app?

**Comment by AbdullahDiaa** [comment]
You can now toggle Notifications on and off without re-register using this function

``` javascript
//Turn off notificaitons
window.plugins.PushbotsPlugin.toggleNotifications(false);
//Enable notificaitons
window.plugins.PushbotsPlugin.toggleNotifications(true);
```
