### ISSUE TITLE
Exception SharedPreferences

### ISSUE THREAD

**Issue by anarfox** [pushbots/phonegap#35]
When I start my Cordova app I get an exception in the LogCat:

04-19 16:20:32.510: E/PluginManager(11803): Uncaught exception from plugin
04-19 16:20:32.510: E/PluginManager(11803): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference
04-19 16:20:32.510: E/PluginManager(11803):     at com.pushbots.google.gcm.GCMRegistrar.getGCMPreferences(GCMRegistrar.java:517)
04-19 16:20:32.510: E/PluginManager(11803):     at com.pushbots.google.gcm.GCMRegistrar.getRegistrationId(GCMRegistrar.java:337)
04-19 16:20:32.510: E/PluginManager(11803):     at com.pushbots.push.Pushbots.regID(Pushbots.java:626)
04-19 16:20:32.510: E/PluginManager(11803):     at com.pushbots.plugin.PushbotsPlugin.execute(PushbotsPlugin.java:68)
04-19 16:20:32.510: E/PluginManager(11803):     at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
04-19 16:20:32.510: E/PluginManager(11803):     at org.apache.cordova.PluginManager.exec(PluginManager.java:133)
04-19 16:20:32.510: E/PluginManager(11803):     at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
04-19 16:20:32.510: E/PluginManager(11803):     at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
04-19 16:20:32.510: E/PluginManager(11803):     at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
04-19 16:20:32.510: E/PluginManager(11803):     at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:39)
04-19 16:20:32.510: E/PluginManager(11803):     at android.os.Handler.dispatchMessage(Handler.java:102)
04-19 16:20:32.510: E/PluginManager(11803):     at android.os.Looper.loop(Looper.java:148)
04-19 16:20:32.510: E/PluginManager(11803):     at android.os.HandlerThread.run(HandlerThread.java:61)
04-19 16:20:32.545: I/PB2(11803): PushBots Library v2.0.14
04-19 16:20:32.548: E/PB2(11803): AndroidManifest.xml missing required permission: android.permission.GET_ACCOUNTS

Worth noting that android.permission.GET_ACCOUNTS is already in the AndroidManifest.
Tested phone: Nexus 6P, Android 6.0.1.

**Comment by akashchavanipru** [comment]
Any resolutions ??

**Comment by akashchavanipru** [comment]
anarfox  have you got any solutions ?

**Comment by eohnuhs** [comment]
Any solution? I'm having same issue and cracking my head for days but cant fix it. Everything was fine previously and suddenly it came out this error where i din make any changes. Anyone know what is the issue?

**Comment by amrsobhy** [comment]
will be resolved in our next update, should come out in a few days

**Comment by AbdullahDiaa** [comment]
Fixed with 1.4.0
