### ISSUE TITLE
Android Build Error: Multiple Dex filed defined, when building with Pushbots plugin with Background-Geolocation plugin

### ISSUE THREAD

**Issue by zaherelrody** [pushbots/phonegap#37]
Dear,

I would be glad if anyone could help with this issue, my app was working fine with pushbots until i installed the plugin https://github.com/transistorsoft/cordova-background-geolocation-lt, the build error states: 
'com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;'
it is because pushbots depends on android-support-4 which uses a .jar file!
How can i resolve this conflict?

**Comment by amrsobhy** [comment]
try to delete android-support-4 existing jar.

**Comment by zaherelrody** [comment]
i tried to but when i re-build the app it downloads it through npm as dependency for pushbots

**Comment by akilud** [comment]
Hello,

I had this same problem where the app would not build due to multiple dex files, Step 1 in this page solved it for me [http://www.thedevline.com/2014/06/unexpected-top-level-exception.html](url)

**Comment by m-vdv** [comment]
Got a similar build error (Conflict with https://github.com/danwilson/google-analytics-plugin).
I can't have Pushbots and Google Analytics plugin or the build fails.
Any simple solution available?

**Comment by zaherelrody** [comment]
I found a workaround for my problem by removing the current Pushbots plugin and installing the following version of it:
[olliebennett-phonegap/Cordova Plugin for Pushbots](https://github.com/olliebennett/phonegap)
This version doesn't have a dependency on android-support-v4 that contains a **.jar** file, which is, as someone advised me, not a good approach for building phonegap/cordova plugins.

**Comment by AbdullahDiaa** [comment]
@zaherelrody  The problem should be fixed with 1.3.9 by using framework instead of dependency.
