### ISSUE TITLE
notification:clicked event never fired until restart app (android)

### ISSUE THREAD

**Issue by strigookuloj** [pushbots/phonegap#38]
This happen only immediately after the app installation in foreground and background. 
After restart app the event fired successfully all the time.

Can you help me?
Thanks

**Comment by AbdullahDiaa** [comment]
Can you please send me more details on Android version/device and copy of logcat with any error in case there're any?

**Comment by AbdullahDiaa** [comment]
This has been fixed with 1.4.0.
