### ISSUE TITLE
Receiving notifications of pushbots/instapush-laravel

### ISSUE THREAD

**Issue by joanebrown** [pushbots/phonegap#40]
Hi!

I'm using your `pushbots/instapush-laravel` package as follow:

`Insta::Push("MyEvent", ['test1'=>'Hi!','test2'=>'1']);`

But I don't know how to use `window.plugins.PushbotsPlugin` to trigger this events...

There is any option to trigget this, get the value of `test1` and `test2` and then send the notification as I want?

Thank you very much!!

Regards!

**Comment by AbdullahDiaa** [comment]
Can you please elaborate more?
