### ISSUE TITLE
Multi-line notification for android devices not available

### ISSUE THREAD

**Issue by hopesourav** [pushbots/phonegap#41]
Hi ,

It will be very nice if Multi-line notification can be done through the cordova/phonegap pushbot plugin.
My app currently generates ~30 letter notification which gets automatically truncated after 1st line.
This happens across all versions android OS.

Regards,
Sourav

**Comment by hopesourav** [comment]
Resolved!
Need to pass the below custom payloads!
"BigTextStyle"=> "true","bigText"=> "XYZ .... "

:)

**Comment by joanebrown** [comment]
Hi! I'm trying to make this, but I don't know how...

Where do you write this `payload`? Inside your server side library or in this plugin?

I will appreciate some help :)

**Comment by hopesourav** [comment]
I did that in the server side library. It just works out of the box!

Refer to the below link for reference :
 https://pushbots.com/developer/docs/android-sdk-integration

**Comment by joanebrown** [comment]
Thanks for your answer! I tried with this, but doesn't work :S

```
$pb = new PushBots();
$pb->App($MyAppID, $MyAppSecret);
$pb->AlertOne($myMessage);
$pb->Payload(array("BigTextStyle"=>true, "bigText"=>"Lorem ipsum bla bla bla..."));
$pb->PlatformOne("1");
$pb->TokenOne($myUserToken);
$pb->PushOne();
```

I am doing something wrong? Thank you very much!

NOTE: This works, I receive the notification, but only one line.

**Comment by hopesourav** [comment]
Pls find our code below. 

```
require_once('PUSH_MSG/PushBots.class.php');
$pb = new PushBots();
$pb->App($appID, $appSecret);
$customfields= array("largeIcon"=>"/img/logo.png","InboxStyleOff" => "true","customNotificationTitle" => "Booking Confirmation","BigTextStyle"=> "true","bigText"=> "Your booking ".$bid." is successfully placed. We will reach out to you shortly with an update on your booking.");
$pb->Payload($customfields);
$pb->Alert("Your booking status is ".$rows[0]["ACTIVE"].".");
$pb->Platform("1");
$pb->Alias($rid);
$temp=$pb->Push();
```

**Comment by joanebrown** [comment]
Thank you very much :)

By the way, you know how to change the color of the circle of notification?

**Comment by hopesourav** [comment]
Actually, I am trying to find that myself. If I get the code, I shall post it here.
Pls post it here if you figure it out first.

:)

**Comment by joanebrown** [comment]
Of course! :D Thank you very much: We keep in touch

**Comment by joanebrown** [comment]
@hopesourav Have you know how to change the color of the circle now? Me not.

I have a question in PushBots paltform but... I have not received answer yet

**Comment by amrsobhy** [comment]
You should add a drawable titled white_notification_icon to your app.
that'll replace the icon for android 5.0+.

The icon should be white-on-transparent background, to quickly generate small icons with the correct settings, we recommend using the Android Asset Studio.
http://romannurik.github.io/AndroidAssetStudio/icons-notification.html

**Comment by joanebrown** [comment]
Hi @amrsobhy  and... do you know where I need to add this image? I don't have idea

**Comment by amrsobhy** [comment]
@joanebrown drawable folder in your Android project

**Comment by joanebrown** [comment]
thnks! i will try it. i using ionic for that. there is any way to do that without change in the platform directory? :)

**Comment by hopesourav** [comment]
@amrsobhy could you pls comment on issue #42 ... I this its a bug :(

**Comment by hopesourav** [comment]
@joanebrown  let me know if can change the color of the icon

**Comment by joanebrown** [comment]
I don't know how to change the color of the circle.. and I have a `white_notification_icon.png` inside my `platforms\android\res\drawable-hdpi` but doesn't work.
