### ISSUE TITLE
getRegistrationId never gets Id

### ISSUE THREAD

**Issue by optikalefx** [pushbots/phonegap#45]
I haven't changed this code in while, it was working before, but now I never get registration IDs.

```
window.plugins.PushbotsPlugin.initialize(config.APP.pushbots.appId, {
    'android': {
        'sender_id': config.APP.pushbots.gcm
    }
});
```

```
window.plugins.PushbotsPlugin.getRegistrationId(function(token){
    console.log("Registration Id:" + token);
});
```

It's always null

**Comment by optikalefx** [comment]
With some debugging, your success is getting called, but with no "data". https://cl.ly/3i3F2B3Z201O

**Comment by amrsobhy** [comment]
What platform are you testing on? Android or iOS?

**Comment by optikalefx** [comment]
iOS 10

**Comment by optikalefx** [comment]
Hey, this is for a client, is there anyway I could pay for some premium support on this? We'd love to have this working again.

**Comment by amrsobhy** [comment]
We are working on reproducing this bug. If you have more info please do share.
