### ISSUE TITLE
Device with iOS 10 not getting registered

### ISSUE THREAD

**Issue by dhwalin** [pushbots/phonegap#46]
I installed plugin, works fine in android. But in iOS device not getting register. Somehow I saw registered device iphone 4s. User might have old iOS. But I having iPhone 5 with iOS 10 not getting registered.

**Comment by amrsobhy** [comment]
We are going to test and reproduce the problem and get back to you as soon as we can.

**Comment by willex** [comment]
Bump, same issue on my side. From what I found it has to do with the Push Notification flag that is now mandatory in XCode 8. Unfortuantely I'm using a build service so I can't set the flag manually. You probably have to update the iOS SDK for that?

**Comment by AbdullahDiaa** [comment]
The problem should be resolved with 1.4.0
