### ISSUE TITLE
Pushbot.on and Pushbot.getRegistrationId callbacks are lost and not giving values

### ISSUE THREAD

**Issue by sultanahmedkhan** [pushbots/phonegap#55]
callback in window.plugins.PushbotsPlugin.on  and window.plugins.PushbotsPlugin.getRegistrationId is not working . My device has registered on the pushbot but in my app i am not getting token.
i am using pushbot version 1.4.1

window.plugins.PushbotsPlugin.on("registered", function(token){
    console.log("Registration Id:" + token);
});

window.plugins.PushbotsPlugin.getRegistrationId(function(token){
        console.log("Registration Id:" + token);
      });

**Comment by AbdullahDiaa** [comment]
@sultanahmedkhan 

Please use latest version of the SDK:

You should be able to get user id and reg id with every run using this method:

```
//Get user registrationId/token and userId on PushBots
window.plugins.PushbotsPlugin.on("user:ids", function(data){
    console.log("user:ids" + JSON.stringify(data));
});
```
