### ISSUE TITLE
cydia

### ISSUE THREAD

**Issue by planetcrypton** [pushbots/phonegap#56]
When the app starts up, I see this in my XCode log.
```
-canOpenURL: failed for URL: "cydia://package/com.example.package" - error: "This app is not allowed to query for scheme cydia"
```
Doing a grep, this seems most likely to come from from a Pushbots source file.
```
cordova/platforms/ios/Friskole & Børnehus/Plugins/pushbots-cordova-plugin/Pushbots.framework/Pushbots
cordova/plugins/pushbots-cordova-plugin/src/ios/libs/Pushbots.framework/Pushbots
```
Is that correct? What does it actually do?

**Comment by AbdullahDiaa** [comment]
It checks if the device is jailbroken or not to send notifications based on jailbreak status.
The warning above can be totally ignored.
