### ISSUE TITLE
initialize and resetting tags?

### ISSUE THREAD

**Issue by planetcrypton** [pushbots/phonegap#57]
I'm experiencing an issue where the tags set by an app, seem to get reset when the app starts up (not resume).
Could it be that calling the initialize() method, resets the tags set at the Pushbots server, or is that out of the question :) ?

**Comment by AbdullahDiaa** [comment]
The problem should be resolved now.

Can you please try agian?

**Comment by planetcrypton** [comment]
Confirmed - problem solved :)
