### ISSUE TITLE
Clicked notifications not being recorded, Alias not being set, etc

### ISSUE THREAD

**Issue by jamminjames** [pushbots/phonegap#58]
Not that anyone seems to be minding the store here, but I'll ask anyway. Our apps' clicked notifications are not being recorded, and the Alias is not being set, among other problems.

The example shown for the code is unclear as to where it belongs. Should it all go in the index.js file, inside the `onDeviceReady: function()` section?

I have these on the app's index page in a script, but it doesn't seem to be doing anything. 

Also, is pushbots.js supposed to be included in the js/ folder and called in the app's index.html head? Or is it installed with the app via the config.xml file by Phonegap Build?

**Comment by meMuhammadkamal** [comment]
Hi jamminjames,

Sometimes if you are using Cordova version that is different than the sample App it won't work as expected so to make sure that the App works fine just create new App using your current version of cordova.

-Then Inside onDeviceReady you should add this line:

`window.plugins.PushbotsPlugin.initialize("App_id", {"android":{"sender_id":"sender_id"}});`

**Comment by jamminjames** [comment]
It's the same Cordova version, and I do have that line in index.js, and the correct App ID, etc are in there. And it is working, as far as devices getting registered. 

However, as I said, clicked notifications are not being recorded, and the Alias is not being set, among other problems, like tags. So, the question is, where do those lines go, exactly? Lines shown in your instructions, such as: 
`window.plugins.PushbotsPlugin.on("notification:clicked", function(data){
    console.log("clicked:" + JSON.stringify(data));
});`
The instructions say, "// Should be called once the notification is clicked," but how do we accomplish that? Or, if the above fires when the notification is clicked, what do we put in the function to notify pushbots?

And: `window.plugins.PushbotsPlugin.setAlias(name);`
Where exactly does that line go? Because it is not working right now, no alias is being set, or at least pushbots is not being informed of the alias, if it is.

**Comment by kevin-finesse** [comment]
I've just been working on an app using this plugin and this is what worked for me - all of this code going inside the onDeviceReady: function() section
`				
window.plugins.PushbotsPlugin.initialize("xxx", {"android":{"sender_id":"yyy"}});
window.plugins.PushbotsPlugin.setAlias("TEST");
window.plugins.PushbotsPlugin.on("notification:received", notification_received);
window.plugins.PushbotsPlugin.on("notification:clicked", notification_clicked);
`

the notification_received(data) and notification_clicked(data) functions then simply receive the data when a notification is received or clicked on.

I found on Android I only needed the notification_clicked function as notifications always get posted to the central notification list and clicking on a notification always calls notification_clicked

On IOS:
- notification_clicked is called if the app isn't running when the notification is clicked
- notification_received is called if the app is running in the background when the notification is clicked
- if the app is in foreground the notification isn't posted to the central notification list but notification_received gets called directly.

hope that helps
Kevin

**Comment by planetcrypton** [comment]
I believe it's a platform version related issue. I all of a sudden can no longer listen to on-notification:clicked events after I upgraded (both cordova and) platform-ios.
I do receive on-notification:received.
I'm using:
Cordova 7.0.1
ios 4.4.0

**Comment by jamminjames** [comment]
Kevin, you say, "the notification_received(data) and notification_clicked(data) functions then simply receive the data when a notification is received or clicked on" ... where are those functions? Is that something we should have in the index.js file, or is that part of the app installed with the config line in Phonegap Build?

**Comment by planetcrypton** [comment]
@jamminjames : In @kevin-finesse 's example `notification_received` and `notification_clicked` are the event-handlers (functions) for resp. on-notification:received and -notification:clicked events.
To be more exact the names of the variables referring to those handlers. You could use an anonymous function if you like :)

**Comment by jamminjames** [comment]
@planetcrypton: Thanks. I wonder if you could tell me the difference in the result of the following lines of code, if they are placed inside the onDeviceReady: function() section. The first one is recommended by Kevin, earlier in this thread, and the other I've seen recommended elsewhere:

`window.plugins.PushbotsPlugin.on("notification:clicked", notification_clicked);`

```
window.plugins.PushbotsPlugin.on("notification:clicked", function(data){
    console.log("clicked:" + JSON.stringify(data));
});
```

The second one will display the data in the console, obviously, but will it send the same info to Pushbots, or will it only display info for the app creator?

**Comment by planetcrypton** [comment]
@jamminjames : It's the exact same thing, look:
```
var notification_clicked = function(data){
    console.log("clicked:" + JSON.stringify(data));
};
window.plugins.PushbotsPlugin.on("notification:clicked", notification_clicked);
```
It's a matter of preference / convenience, whether you'd like to reuse the handler elsewhere, make your code more readable or not - as long as you can access the `notification_clicked`, in the 'scope' you're attaching it to the event

**Comment by jamminjames** [comment]
I'm still confused, though, because in your example, you're setting the variable, whereas if I only put in the line `window.plugins.PushbotsPlugin.on("notification:clicked", notification_clicked);` without setting the variable, it wouldn't do the same thing. Unless, since I'm using the pushbot plugin, they already have that variable set in their code. Correct?

**Comment by planetcrypton** [comment]
If you're using `window.plugins.PushbotsPlugin.on("notification:clicked", notification_clicked);` in your `onDeviceReady`-handler function, the variable `notification_clicked` will have to be defined somewhere: either in your `onDeviceReady` function's scope, or global scope (if you're not importing it as a module...).
You asked whether PushBots has defined it in their plugin: I haven't checked, but can't imagine why - `notification_clicked` will define what has to happen in your app, when a push-notification-alert gets entered (=being clicked/swiped) by the app user (perhaps routing your app to a specific route??)

So as long as you don't define `notification_clicked` I expect nothing to happen (apart from your app actually encounters an error: notification_clicked is undefined). What result do you get?

**Comment by jamminjames** [comment]
Okay, thanks for the clarification. One last question, if I may, do you happen to know what this does? I have it in the deviceready function, inside the `notification:received` sub-function, as I saw it recommended somewhere:
`window.plugins.PushbotsPlugin.done(data.pb_n_id);` - does this report info to Pushbots? Before I started using it, Pushbots didn't seem to be getting info on how many had received the notifications, but now it does. So I'd just like to verify, if I can, that this is what this line is doing. If so, should I put the same line, or something similar, in the `notification:clicked` function?

**Comment by planetcrypton** [comment]
What it does, is making it a 'silent notification' (only available in iOS). I've never used it myself and thus don't know too much about it, but happen to read it in the readme file of this repo (##Usage 2.)

**Comment by jamminjames** [comment]
Ah, I see. Thanks for all your help -- it's hard to get any answers from the pushbots folks on their site.

**Comment by planetcrypton** [comment]
Long live the community!
