### ISSUE TITLE
Click on received notification reopen application even if it's already running

### ISSUE THREAD

**Issue by ahmedelrefaiy** [pushbots/phonegap#67]
when i click on received notification >> it always reopens the application again, so if i aleady have instance of my application opened, it will be removed and application starts again

i think this error happed related to these lines in the plugin

//Start Launch Activity
String packageName = context.getPackageName();
Intent resultIntent = new Intent(context.getPackageManager().getLaunchIntentForPackage(packageName));
resultIntent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK| Intent.FLAG_ACTIVITY_CLEAR_TASK);

I think these lines need specific lunch mode to work with??

**Comment by sarbona** [comment]
I have the same problem.

I even opened a new issue #69 which has been closed but the problem remains.
