### ISSUE TITLE
Pushbots with surprising little info for paid package

### ISSUE THREAD

**Issue by NgYueHong** [pushbots/phonegap#7]
Hi,

I am writing it here because I can't find a way to contact to PushBots from it's website (There is no contact us page!!!). I have opened conversation in my free account, but so far I get no respond at all from them. Feels like they don't want to do business?

What I want to ask is:
1. On the pricing page, it only listed the limitation on the number of push message, but why is that in my free account there is the limitation of usage in API? So, how much will be the API usage limitation for all other paid packages?
2. Regarding the limitation, is it the hard limit or it will be additional charges when over use? For example, if I am getting basic package and I push 6 millions message that month. What would happen? Hard limit? If not, what is the charges for the additional 1 millions push?
3. From the FREE account, the number of app can be used is unlimited. Does it still be unlimited for ultimate package? If yes, then is that mean I can use with ten to hundreds of app with unlimited push, almost everything is unlimited for just $249 per month?
4. Is there any place that I can find more complete info about packages? If possible please make things more transparent.
5. Is there any way to better direct contact with PushBots? It is the first time ever I saw website with such little info that is almost no way to contact.

**Comment by amrsobhy** [comment]
Already answered on your PushBots account.
