### ISSUE TITLE
notification:clicked not firing on iOS 10 & 11 if resuming the app from background

### ISSUE THREAD

**Issue by anarfox** [pushbots/phonegap#75]
notification:clicked only fires when clicking the notification if the app isn't already in the background.

If it is, notification:received is fired instead but that isn't an option since this is also called when receiving a push if the app is open and you might want a different behaviour for that scenario.

**Comment by AbdullahDiaa** [comment]
@anarfox when application is open you received should be fired first, then you'll get a notification inside the app, if you click on open, clicked will be then fired.

Can you please send me exact scenario to reproduce your problem and the fix proposed?
What do you mean by " isn't already in the background" ? do you mean closed completely or on foregound or both?

**Comment by AbdullahDiaa** [comment]
Fixed in 1.5.15
