### ISSUE TITLE
Build failed with message "Multiple dex files define" after install "admobpro" plugin with "pushbots" plugin

### ISSUE THREAD

**Issue by ahmedelrefaiy** [pushbots/phonegap#78]
after install "**admobpro**" plugin [https://github.com/floatinghotpot/cordova-admob-pro](url)  with pushbots, i get this error "**Multiple dex files define Lcom/google/android/gms/common/api/internal/zza**"

according to "**admobpro**" plugin, "**pushbots**" plugin have an error with using "com.google.playservices"- this link contain the case: [https://github.com/floatinghotpot/cordova-admob-pro/wiki/Difference-of-Plugin-IDs#3-build-error-with-message-multiple-dex-files-define-lcomgoogle](url)

**Comment by ahmedelrefaiy** [comment]
this is the whole error message:

1>MSBUILD : cordova-build error : Execution failed for task ':transformClassesWithDexForDebug'.
1>MSBUILD : cordova-build error : > com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/common/api/internal/zza;

**Comment by ahmedelrefaiy** [comment]
i'm waiting your reply @AbdullahDiaa

**Comment by joerischepers** [comment]
Got the same problem when using pushbots plugin with cordova and addmob-pro...
Any solution yet?

**Comment by AbdullahDiaa** [comment]
This should be fixed with 1.6.2
