### ISSUE TITLE
Detect if its active/registered

### ISSUE THREAD

**Issue by zesschrno** [pushbots/phonegap#82]
In the documentation I cannot find a method that returns a Boolean value in which it detects if the pushbots instance is active or if the device is registered.

Something like this:

`window.plugins.PushbotsPlugin.isInitialized() // returns a boolean value or promise`
`window.plugins.PushbotsPlugin.isRegistered() // returns a boolean value or promise`

**Comment by ibrahimAlii** [comment]
Hi @zesschrno sorry for late response.
Your request will published in the next release soon.

Thank you.

**Comment by jordan-thenumber** [comment]
any chance this will ever get released?
